#!/usr/bin/env bash
# dingsbums installer — installs the latest GitHub release's dingsbums.jar
# into ~/.dingsbums (a directory this installer fully manages: reinstalls
# replace it) and a launcher into ~/.local/bin/dingsbums.
#
#   curl -fsSL https://raw.githubusercontent.com/sstoehrm/dingsbums/main/install.sh | bash
#
# Env overrides: DINGSBUMS_HOME (default ~/.dingsbums),
#                DINGSBUMS_BIN  (default ~/.local/bin),
#                DINGSBUMS_JAR  (a local jar to install instead of the
#                                latest release; for testing)
set -euo pipefail

REPO="sstoehrm/dingsbums"
JAR_URL="https://github.com/$REPO/releases/latest/download/dingsbums.jar"
DINGSBUMS_HOME="${DINGSBUMS_HOME:-$HOME/.dingsbums}"
BIN_DIR="${DINGSBUMS_BIN:-$HOME/.local/bin}"
MIN_BB="1.12.0"

die() { echo "install: $*" >&2; exit 1; }

check_deps() {
  local have
  command -v curl >/dev/null 2>&1 || die "curl is required"
  command -v bb >/dev/null 2>&1 \
    || die "babashka (bb) not found — install it from https://babashka.org"
  have=$(bb --version | sed -E 's/[^0-9.]//g')
  [ "$(printf '%s\n' "$MIN_BB" "$have" | sort -V | head -n1)" = "$MIN_BB" ] \
    || die "babashka $have is too old (need >= $MIN_BB)"
}

install_jar() { # sets VERSION
  # deliberately not `local`: the EXIT trap runs after this function's
  # scope is gone, so the variable must survive it
  tmp=$(mktemp -d)
  trap 'rm -rf "$tmp"' EXIT
  if [ -n "${DINGSBUMS_JAR:-}" ]; then
    cp "$DINGSBUMS_JAR" "$tmp/dingsbums.jar"
  else
    echo "downloading $JAR_URL"
    curl -fsSL "$JAR_URL" -o "$tmp/dingsbums.jar" || die "could not download $JAR_URL"
  fi
  VERSION=$(bb -cp "$tmp/dingsbums.jar" -e '(print (clojure.string/trim (slurp (clojure.java.io/resource "VERSION"))))') \
    || die "the downloaded file is no dingsbums jar"
  rm -rf "$DINGSBUMS_HOME"
  mkdir -p "$DINGSBUMS_HOME"
  cp "$tmp/dingsbums.jar" "$DINGSBUMS_HOME/dingsbums.jar"
  echo "$VERSION" >"$DINGSBUMS_HOME/VERSION"
}

write_launcher() {
  mkdir -p "$BIN_DIR"
  cat >"$BIN_DIR/dingsbums" <<'LAUNCHER'
#!/usr/bin/env bash
# dingsbums launcher — generated by install.sh; reinstalling overwrites it.
# It keeps `update`, which belongs to this install, and hands everything
# else to the CLI in the installed jar.
set -euo pipefail

DINGSBUMS_HOME="${DINGSBUMS_HOME:-$HOME/.dingsbums}"
API_URL="https://api.github.com/repos/sstoehrm/dingsbums/releases/latest"

die() { echo "dingsbums: $*" >&2; exit 1; }

version() { cat "$DINGSBUMS_HOME/VERSION" 2>/dev/null || echo "unknown"; }

update() {
  local latest installer
  latest=$(curl -fsSL "$API_URL" | grep -m1 '"tag_name"' \
           | sed -E 's/.*: *"([^"]+)".*/\1/') \
    || die "could not query the latest release"
  [ -n "$latest" ] || die "could not read the latest release tag"
  if [ "$latest" = "$(version)" ]; then
    echo "dingsbums $(version) is already up to date"
  else
    echo "updating $(version) -> $latest"
    # run the new release's installer, never a stored copy: an installer
    # writes the launcher embedded in itself, so an old one would keep
    # reinstalling its old launcher
    installer=$(mktemp)
    curl -fsSL "https://raw.githubusercontent.com/sstoehrm/dingsbums/$latest/install.sh" \
      -o "$installer" || { rm -f "$installer"; die "could not download the $latest installer"; }
    DINGSBUMS_HOME="$DINGSBUMS_HOME" bash "$installer"
    rm -f "$installer"
  fi
}

case "${1:-}" in
  update) update ;;
  *)
    command -v bb >/dev/null 2>&1 \
      || die "babashka (bb) not found — install it from https://babashka.org"
    [ -f "$DINGSBUMS_HOME/dingsbums.jar" ] \
      || die "$DINGSBUMS_HOME/dingsbums.jar not found — run install.sh again"
    # -cp: a bb.edn in the caller's folder is not loaded
    exec bb -cp "$DINGSBUMS_HOME/dingsbums.jar" -m dingsbums.cli "$@"
    ;;
esac
LAUNCHER
  chmod +x "$BIN_DIR/dingsbums"
}

main() {
  check_deps
  install_jar
  write_launcher
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "note: $BIN_DIR is not on your PATH — add it to use 'dingsbums'" ;;
  esac
  echo "installed dingsbums $VERSION"
  echo "  files:    $DINGSBUMS_HOME"
  echo "  launcher: $BIN_DIR/dingsbums"
  echo "try: dingsbums"
}

main "$@"
